version: '3'

services:
  mariadb:
      image: mariadb
      volumes:
        - ./data/mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_DATABASE: keycloak
        MYSQL_USER: $DB_USERNAME
        MYSQL_PASSWORD: $DB_PASSWORD
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
      restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8183:80
  keycloak:
      build: ./config/docker/
      # For ARM64 servers
      # image: richardjkendall/keycloak-arm
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD
        KEYCLOAK_USER: $kc_user
        KEYCLOAK_PASSWORD: $kc_pw
        JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      restart: unless-stopped
      volumes:
        # - ./config/lttr-login-theme/:/opt/jboss/keycloak/themes/lttr-login-theme/
        - ./config/serendipity-keycloak-theme/theme/:/opt/jboss/keycloak/themes/serendipity-keycloak-theme/
      depends_on:
        - mariadb
      ports:
        - '8080:8080'
        - '8443:8443'
  mongodb:
      build: ./config/mongo
      container_name: 'mongo'
      ports:
          - "27017-27019:27017-27019"
      restart: unless-stopped
      environment:
        MONGO_INITDB_ROOT_USERNAME: 'lttr'
        MONGO_INITDB_ROOT_PASSWORD: 'wh4t4reUlooking4'
        MONGO_INITDB_DATABASE: 'lttr'
      volumes:
        - ./data/mongo_data:/data/db

volumes:
  mysql_data:
      driver: local
