mongodb:
  host: 
  dbname: 
  username: 
  password: 

mysql:
  DB_CONNECTION: 
  DB_HOST: 
  DB_PORT: 
  DB_DATABASE: 
  DB_USERNAME: 
  DB_PASSWORD: 
  DB_ROOT_PASSWORD: 

keycloak:
  user: 
  password: 

appUrl: 
apiUrl: 
keycloakUrl: 